version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql
    container_name: "laravel-mysql"
    volumes:
            - ./mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
    ports: 
      - 13306:3306